//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewCookbook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRecipe
    {
        public int Recipe_Id { get; set; }
        public string Recipe_Category { get; set; }
        public string Recipe_name { get; set; }
        public string Recipe_Description { get; set; }
        public Nullable<System.DateTime> Recipe_Date { get; set; }
    }
}
